# Note: In our experiment, we used the same LD score files for --ref-ld and --w-ld

./ldsc.py --rg MUNGED_SUMSTATS_FOR_TRAIT_1,MUNGED_SUMSTATS_FOR_TRAIT_2 --ref-ld LD_SCORE_FILE_FOR_INDEPENDENT_VARIABLE --w-ld LD_SCORE_FILE_FOR_REGRESSION_WEIGHTS --out OUTPUT_DIRECTORY_FOR_HERITABILITY_AND_GENETIC_COVARIANCE
